remove jq

diff --git a/.github/workflows/generate_release_pdf.yml b/.github/workflows/generate_release_pdf.yml
--- a/.github/workflows/generate_release_pdf.yml
+++ b/.github/workflows/generate_release_pdf.yml
@@ -21,21 +21,20 @@ jobs:
       - name: Set up Git repository for secondary repo
         uses: actions/checkout@v4
      
-      - name: Install jq if not present
-        run: |
-          if ! command -v jq &> /dev/null
-          then
-            echo "jq could not be found, installing..."
-            sudo apt-get install -y jq
-          fi
+      # - name: Install jq if not present
+      #   run: |
+      #     if ! command -v jq &> /dev/null
+      #     then
+      #       echo "jq could not be found, installing..."
+      #       sudo apt-get install -y jq
+      #     fi
     
       # - name: Prepare directories
       #   run: |
       #     mkdir -p ./cv
       #     mkdir -p ./fonts
 
-      - name: Install jq
-        run: sudo apt-get install jq
+
 
       # - name: Download Metadata
       #   run: |
