debug

diff --git a/.github/workflows/generate_release_pdf.yml b/.github/workflows/generate_release_pdf.yml
--- a/.github/workflows/generate_release_pdf.yml
+++ b/.github/workflows/generate_release_pdf.yml
@@ -23,13 +23,44 @@ jobs:
      
       - name: Install Fonts
         run: |
-          wget -O Noto_Sans_SC.zip https://fonts.google.com/download?family=Noto%20Sans%20SC
+          if ! command -v jq &> /dev/null
+          then
+            echo "jq could not be found, installing..."
+            sudo apt install -y jq
+          fi
+
+          mkdir -p /cv
+
+          # Download Sarabun font metadata
+          curl -s "https://fonts.google.com/download/list?family=Noto%20Sans%20SC" > cv/noto_sans_sc_raw.txt
+
+          # Remove ")]}'" from the beginning of the file
+          tail -c +5 cv/noto_sans_sc_raw.txt > cv/noto_sans_sc_metadata.json
+
+          # Extract the necessary information from the JSON file
+          file_refs=$(jq -rc '.manifest.fileRefs[]' cv/noto_sans_sc_metadata.json)
+
+          mkdir -p /fonts
+
+          # Download, rename the font files and save to /fonts
+          while IFS= read -r file_ref; do
+              filename=$(echo "$file_ref" | jq -r '.filename')
+              url=$(echo "$file_ref" | jq -r '.url')
+              curl -s "$url" -o "/fonts/$filename"
+          done <<< "$file_refs"
+
+          rm cv
+
           echo "Font downloaded."
-          ls -l
-          file Noto_Sans_SC.zip
-          unzip -d Noto_Sans_SC/ Noto_Sans_SC.zip
-          mv Noto_Sans_SC/static /usr/share/fonts/
-          fc-cache -fv
+
+          ls -l /fonts/
+
+          # file Noto_Sans_SC.zip
+          # unzip -d Noto_Sans_SC/ Noto_Sans_SC.zip
+          # mv Noto_Sans_SC/static /usr/share/fonts/
+          # fc-cache -fv
+
+
 
       - name: Check Fonts Existence
         id: check-fonts
